

CREATE DATABASE esquina_do_acai;

USE esquina_do_acai;

CREATE TABLE usuario(
    id_usuario BIGINT(6) ZEROFILL AUTO_INCREMENT NOT NULL,
    nome VARCHAR(40) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    email VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    endereco VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    cep INT(20) NOT NULL,
    cpf INT(20)  NULL,
    senha VARCHAR(20) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    CONSTRAINT pkid_usuario PRIMARY KEY(id_usuario));