

CREATE DATABASE esquina_do_acai;

USE esquina_do_acai;

CREATE TABLE person(
    id_person BIGINT(6) ZEROFILL AUTO_INCREMENT NOT NULL,
    b_name VARCHAR(40) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    b_email VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    b_zipCode INT(20) NOT NULL,
    b_number INT NOT NULL,
    b_complement INT NULL,
    b_endereco VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    b_cpf INT NOT NULL,
    b_password VARCHAR(20) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    b_type ENUM('adm', 'user') CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    CONSTRAINT pkid_person PRIMARY KEY(id_person));